[package]
name = "ex_lib"
version = "0.1.0"
edition = "2021"

[dependencies]
hex = "0.4.3"
hmac = "0.12.1"
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0.151", features = ["derive"] }
sha2 = "0.10.6"
reqwest = "0.11.13"
async-trait = "0.1.60"